### ISSUE TITLE
Undefine, and unmacro

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#133]
They let you do some fun tricks, and it could be useful in a situation where code conflicts.

**Comment by ghost** [comment]
I want to change this to local defines, and local macros...

**Comment by kierenj** [comment]
In theory you can already make a #define or #macro within a file which would override one from another project.  Because the files are not put through a preprocessor per se (where macros, defines etc need to appear before any references to them), this is less applicable I think.  Will leave this issue here and think about it a little later on I think

**Comment by ghost** [comment]
Well with a top down approach you could do something similar to the labels, where you have local, and global defines, and macros

**Comment by kierenj** [comment]
What I have in mind is not to allow conflicting code, and force some good coding practises.  This isn't a classic-style assembler (w/ separate preprocessor), it performs a lot of analysis which enables cross-language, cross-project and cross-file references.  #undef/#unmacro etc don't fit into this idea at the moment
