### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by janbaykara** [kierenj/0x10c-DevKit#145]
So we can compile it for Mac? :)

**Comment by kierenj** [comment]
Hi, there is another issue here addressing that which I will link when I can.  It's Windows only at the moment due to cross platform .NET technologies like Wine or Mono not supporting WPF.

Sent from Samsung Galaxy Note

-------- Original message --------
Subject: [0x10c-DevKit] Source code (#145) 
From: JanBaykara reply@reply.github.com 
To: Kieren Johnstone kierenj@gmail.com 
CC:  

So we can compile it for Mac? :)

---

Reply to this email directly or view it on GitHub:
https://github.com/kierenj/0x10c-DevKit/issues/145

**Comment by janbaykara** [comment]
Understood, thanks for the reply :)
