### ISSUE TITLE
Can use DCPU-Stress-Test as a source of some unit tests

### ISSUE THREAD

**Issue by ghost** [kierenj/0x10c-DevKit#157]
It cannot currently assemble these tests

https://github.com/SirCmpwn/DCPU-Stress-Test

**Comment by kierenj** [comment]
Some of them are not meant to assemble, and some of them have directives intended for other assemblers (because there is no 'standard' in use).  However, unit tests are coming for devkit and _parts_ of these might become parts of unit tests.  I am going to adjust the title here, and it will be prioritised at some point for inclusion. Thanks :)
