### ISSUE TITLE
Installerless binaries

### ISSUE THREAD

**Issue by ThaPear** [kierenj/0x10c-DevKit#160]
I would really like to see a release without an installer, as I prefer not to install anything.

**Comment by kierenj** [comment]
Hi!  I did this once, and due to security problems and a few other user errors, I spent about an hour or two in total debugging/investigating things unnecessarily.  That time could have been spent writing features.  For example, it's necessary to 'unblock' the .exe and .dll files after extracting from an archive.  If you have a proposal for dealing with that, I'm all ears.. but I would prefer to focus on features rather than hand-holding support :)

**Comment by kierenj** [comment]
Ok, well if you think of something, or can convince me, let me know and I will re-open this :)
