### ISSUE TITLE
Value of PC emulated inaccurately

### ISSUE THREAD

**Issue by asterick** [kierenj/0x10c-DevKit#46]
PC is updated and resolved thusly

1) Load op as mem[pc++]
2) get effective address of field A (increment PC when immediate is used)
3) load A with effective address A
4) get effective address of field B (increment PC when immediate is used)

IE:

SET 0x8000, A   will set   (instruction address+1) to the value of A (as EA of field A = op_addr +1)
Like wise:

ADD PC, -1 will halt the CPU (as data of field A is the value of PC after instruction is incremented, even if field B is an 16-bit immediate)

SET PC, PC is effectively a NOP

**Comment by kierenj** [comment]
Hi, thanks for this, will investigate but it's not very clear.  Are you describing expected behaviour or observed behaviour?  Looking through the code and your examples, it seems that the two match (in theory) exactly - things are resolved and incremented in the correct order at the correct time.

SET 0x8000, A should not compile (attempting to write to a literal operand) - and "SUB PC, 1" or "ADD PC, -1" do work as you describe (which is correct).

I would like to see if you have a particular problem or example, and I'll see to it that it's emulated correctly - a couple of quick examples and test cases would be great, if you have the time please?

**Comment by asterick** [comment]
The SET 0x8000, A is "technically" valid assembly.  I've not actually tried it, as the usefulness is basically zero.  The behavior I've noticed in 1.1 is that "SET PC, PC" will cause a closed loop and lock your program.  When I did a step-through on :

ADD PC, -1 
SET PC, PC

It halted on the 2nd line, not the first.

**Comment by asterick** [comment]
Okay, I'm apparently smoking something because it is no longer doing it.  Maybe stale code?

**Comment by kierenj** [comment]
In the current release version, if you step past the end of your code, the last line of code will remain highlighted despite PC changing beyond it. BThe new version will show a disassembly view (recognising that no user code is associated with the new PC value).  Could that be the case here?

Thanks
Kieren

**Comment by asterick** [comment]
There really is no telling.  It could have been that I was executing code, edited it, but didn't reassemble the result.  Either way, everything is peachy.
