### ISSUE TITLE
Negative literals

### ISSUE THREAD

**Issue by BenSheftel** [kierenj/0x10c-DevKit#61]
If the assembly includes a negative literal, for example:
IFE -1, 1
Then building the code produces an error:
Error   InternalBuildException  Error building file Jumble.10c: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index   (none)  0

**Comment by kierenj** [comment]
Hi, this is the case for the first operand only, a workaround is to use brackets or 0-1.  Will be fixed for the next release.  (I am assuming you are using 1.7 preview?)

Thanks
Kieren

**Comment by BenSheftel** [comment]
Yes thanks.

**Comment by kierenj** [comment]
Fixed in the latest build (and will be in next release).  Thanks for the feedback.  For information, the unit test for this ensures the following expressions are parsed OK.  Moving forward these should be 'safe'.  If you can think of any more, please let me know:

set j, 2*-1
set x, -1
:label1
ifn a, 0x8000 + (32-1) \* 12
:label2
ife z, label1 - label2
ife z, label1 -label2
ife z, label1-label2
ife z, label1- label2
ife z, label2 - label1
set x, -label2
ife label1 - label2, z
ife label1 -label2, z
ife label1-label2, z
ife label1- label2, z
ife label2 - label1, z
ife -label2, z
ife -1, z
ife - label2, z
ife - 1, z
ife -1, - 1

**Comment by BenSheftel** [comment]
One followup issue:
IFA 0, -1 does not function correctly
IFA 1, 0 does function correctly
SET A, -1
IFA 0, A does function correctly

There must be an underlying issue with negative literals, but I'm not sure if you've fixed it with the change you made to solve my previous issue.

**Comment by kierenj** [comment]
Wow, that's a good find.  "IFA 0,-1" assembles incorrectly to "IFA B,0".  I imagine there's an underflow/overflow.  Will fix this now.  Thanks!

**Comment by kierenj** [comment]
Phew, thanks: this is fixed for the next release, now.  The following work:

``````
ifa 0,-1
    add b,1

ifa -1,0
    add c,1

ifa 1,0
    add b,1

ifa 0,1
    add c,1

set a,-1
ifa 0,a
    add b,1

ifa a,0
    add c,1
    ```
``````
