### ISSUE TITLE
Keyboard interrupts not properly triggered for all keys

### ISSUE THREAD

**Issue by tyrel** [kierenj/0x10c-DevKit#72]
According to the keyboard spec from Notch:

> When interrupts are enabled, the keyboard will trigger an interrupt when one or more keys have been pressed, released, or typed.

While this isn't entirely clear, your emulator currently sends pressed and released interrupts for special keys, but only sends one interrupt for alphanumeric keys. I think it should be consistent and send interrupts any time any key is pressed or released.

If Notch said something otherwise elsewhere, please point me to it.

**Comment by kierenj** [comment]
I'm looking at Notch's emulator reference code (from RC1).  For key-pressed or key-released, events, an interrupt is only fired if there exists a key mapping for it: and alphanumeric keys do not have a key mapping.  Furthermore, the 'is key pressed' keyboard map does not store the state of alphanumeric (or otherwise ASCII-printable) keys.  I will try posting a comment in the Reddit post about RC1.

**Comment by tyrel** [comment]
Okay, thanks.

**Comment by kierenj** [comment]
For the time being I will keep the behaviour as it is.. it's likely to change or be confirmed one way or another fairly soon I would imagine anyway.  The next release will still not trigger an interrupt for general key-up events.  I hope that's OK: just trying to keep maximum compatibility for now

**Comment by tyrel** [comment]
That's fine.

**Comment by kierenj** [comment]
I'm going to close this for now, and will re-address / investigate when the next release is available from Notch :)
